### ISSUE TITLE
Did you have publish these tutorials to the GitHub Pages?

### ISSUE THREAD

**Issue by shangchihh** [aliyun/devops-tutorials#1]
Did you have publish these tutorials to the GitHub Pages? What is the url?

**Comment by marcplouhinec** [comment]
Hi! I just uploaded them in branches for the moment.
https://github.com/aliyun/devops-tutorials/tree/getting_started_with_devops_with_kubernetes/getting_started_with_devops_with_kubernetes

https://github.com/aliyun/devops-tutorials/tree/DevOps_for_small-to-medium_web_applications/devops_for_small_to_medium_web_applications


    Le jeudi 25 octobre 2018 à 17:28:08 UTC+8, Shang-Chih Raphael Huang <notifications@github.com> a écrit :  
 
 
Did you have publish these tutorials to the GitHub Pages? What is the url?
